### PR TITLE
Add minimal final volume data and constraints

### PR DESCRIPTION
**Pull request by Thiago-NovaesB**
This commit adds the possibility of choosing a minimum volume for the reservoir at the end of the horizon. This can be used to avoid the "end of the world" effect. A test has also been added.

### CODE REVIEW

**Comment by andrewrosemberg** [comment]
Dito on description and tests.

**Comment by Thiago-NovaesB** [comment]
@andrewrosemberg done

**Comment by odow** [comment]
You could also look at using an infinite horizon model

**Comment by andrewrosemberg** [comment]
> You could also look at using an infinite horizon model

@Thiago-NovaesB Shall we create an issue to remember this feature "request"?

**Review by andrewrosemberg — APPROVED** [review]
LGTM

**Comment by andrewrosemberg** [comment]
Approved already, but rebase first and resolve conflicts.

**Pull request merged**
